version: '3'

services:

  db:
    image: mysql:8.0.23
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "scrumpoker"
       MYSQL_USER: "root"
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password

  web:
    build: ./server/
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:8080"
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    depends_on:
      - db

  redis:
    image: redis:6.0.9
    ports:
     - "6379:6379"
    command: redis-server