version: '3'

services:
  web:
    build: .
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    command: bash -c "cd scrumpoker && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nodejs:
    image: node:12.14.1
    tty: true
    expose:
      - "3000"
    ports:
      - "3000:8080"
    volumes:
      - ./client:/client
    working_dir: /client
    command: bash -c "cd scrumpoker && npm install && npm run serve"