version: '3'

services:
  web:
    build: .
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    command: bash -c "cd server/scrumpoker && python manage.py runserver"

  nodejs:
    image: node:12.14.1
    tty: true
    expose:
      - "3000"
    ports:
      - "3000:8080"
    volumes:
      - ./client:/client
    command: bash -c "cd client/scrumpoker && npm install && npm run serve"