version: '3'

services:

  db:
    image: mysql:8.0.23
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "scrumpoker"
       MYSQL_USER: "root"
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --user=root --default-authentication-plugin=mysql_native_password

  web:
    build: .
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env
    command: bash -c "cd scrumpoker && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  nodejs:
    image: node:12.14.1
    tty: true
    expose:
      - "3000"
    ports:
      - "3000:8080"
    volumes:
      - ./client:/client
    working_dir: /client/scrumpoker
    command: bash -c "npm install && npm run serve"

  redis:
    image: redis:6.0.9
    ports:
     - "6379:6379"
    command: redis-server