# Generated by Django 3.1.5 on 2021-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_player_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
