# Generated by Django 3.1.5 on 2021-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_player_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
